services:
  image-advisor:
    build: .
    container_name: image-advisor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - INTERVAL=10
    ports:
      - 8080:8080
